pattern test_throw {
    try {
        x = 42
        throw "Something went wrong!"
        y = 10  // This won't execute
    }
    catch (error) {
        caught_message = error
    }
}
